#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/2.5.0/

* Outline
  - Hypermedia
  - APIs
  - Yaks
  - Demo

* Dictionary definitions

*** hy·per·me·dia
*** [[http://www.merriam-webster.com/dictionary/hypermedia][Merriam-Webster]]
    - hypermedia :: a database format similar to hypertext in which text, sound, or video images
                    related to that on a display can be accessed directly from the display
    - First Known Use :: 1965
    - hypertext :: an arrangement of the information in a computer database that allows a user to
                   get information and to go from one document to another by clicking on highlighted
                   words or to go from one document to another by clicking on highlighted words or
                   pictures
*** [[http://www.oxforddictionaries.com/definition/english/hypermedia?q%3Dhypermedia][Oxford]]
    - hypermedia :: An extension to hypertext providing multimedia facilities, such as those
                    handling sound and video.
    - origin :: 1960s: from hyper- 'above, beyond' + media1.
    - hypertext :: A software system allowing extensive cross-referencing between related sections
                   of text and associated graphic material:
*** [[http://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven#comment-718][Roy Fielding]]
    - hypertext :: When I say hypertext, I mean the simultaneous presentation of information and
                   controls such that the information becomes the affordance through which the user (
                   or automaton) obtains choices and selects actions… Hypertext does not need to be
                   HTML on a browser. Machines can follow links when they understand the data format
                   and relationship types. –Roy Fielding

    - The central feature that distinguishes the REST architectural style from other network-based
                   styles is its emphasis on a uniform interface between components

    - In order to obtain a uniform interface, multiple architectural constraints are needed to guide
                   the behavior of components. REST is defined by four interface constraints:
                   identification of resources; manipulation of resources through representations;
                   self-descriptive messages; and, hypermedia as the engine of application state.

    - The key abstraction of information in REST is a resource. Any information that can be named
                   can be a resource: a document or image, a temporal service (e.g. "today's weather
                   in Los Angeles"), a collection of other resources, a non-virtual object (e.g. a
                   person), and so on. In other words, any concept that might be the target of an
                   author's hypertext reference must fit within the definition of a resource. A
                   resource is a conceptual mapping to a set of entities, not the entity that
                   corresponds to the mapping at any particular point in time.

    -  REST components perform actions on a resource by using a representation to capture the
                   current or intended state of that resource and transferring that representation
                   between components.

       | Data Element            | Modern Web Examples                                     |
       |-------------------------+---------------------------------------------------------|
       | resource                | the intended conceptual target of a hypertext reference |
       | resource identifier     | URL, URN                                                |
       | representation          | HTML document, JPEG image                               |
       | representation metadata | media type, last-modified time                          |
       | resource metadata       | source link, alternates, vary                           |
       | control data            | if-modified-since, cache-control                        |

*** [[http://en.wikipedia.org/wiki/Hypermedia][Wikipedia]]
    + hypermedia :: Hypermedia, an extension of the term hypertext, is a nonlinear medium of information which includes graphics, audio, video, plain text and hyperlinks.

*** [[http://stackoverflow.com/questions/671118/what-exactly-is-restful-programming][StackOverflow]]


    - REST :: using the various HTTP methods (mainly GET/PUT/DELETE) to manipulate data.
              Rather than using a specific URL to delete a method (say, /user/123/delete), you would
              send a DELETE request to the /user/[id] URL, to edit a user, to retrieve info on
              a user you send a GET request to /user/[id]

              For example, instead a set of URLs which might look like some of the following..

              GET /delete_user.x?id=123
              GET /user/delete
              GET /new_user.x
              GET /user/new
              GET /user?id=1
              GET /user/id/1

              You use the HTTP "verbs" and have..

              GET /user/2
              DELETE /user/2
              PUT /user

** Links
*** Reference
    - [[http://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm][Fielding: REST Architectural Style]]
*** Further Reading
    - [[http://blueprintforge.com/blog/2012/01/01/a-short-explanation-of-hypermedia-controls-in-restful-services/][A Short Explanation of Hypermedia Controls in RESTful Services]]
