require 'slippery'

MD='hypermedia'

Slippery::RakeTasks.new do
  title "Building Hypermedia APIs with Yaks | @plexus"
  type :deck_js
  add_highlighting

  # Fathom
  # js_options scrollLength: 0, displayMode: 'single'

  # Deck.js
  js_options extensions: ['navigation'], theme: nil, transition_theme: nil

  pack_assets

  processor 'head' do |head|
    H[:head, head.attributes, head.children + [
        H[:meta, charset: 'utf-8'],
        H[:meta, name: 'viewport', content: 'width=1024'],
        H[:meta, "http-equiv" => 'X-UA-Compatible', content: 'IE=edge,chrome=1'],
        H[:link, rel: 'stylesheet', type: 'text/css', href: 'css/normalize.css'],
        H[:link, rel: 'stylesheet', type: 'text/css', href: 'css/style.css'],
      ]
    ]
  end

  processor 'img' do |img|
    path = 'img/' + img.attr('src')
    img = img.attr('src', path) if File.exist?(path)
    img
  end

  processor '.bullet-points li' do |para|
    para.add_class('slide')
  end
end

desc 'invoke slippery:build'
task :default => 'slippery:build:' + MD

desc 'invoke slippery:watch'
task :watch   => 'slippery:watch:' + MD
