#source 'https://rubygems.org'

gem 'hexpress',
  #github: 'plexus/hexpress',
  path: '/home/arne/github/hexpress',
  branch: 'eurucamp2013'

gem 'hexp',
  #github: 'plexus/hexpress',
  path: '/home/arne/github/hexp',
  branch: 'eurucamp2013'

gem 'kramdown',
  path: '/home/arne/github/kramdown'

gem 'rake'
gem 'rb-inotify'
