require 'hexpress'


namespace :hexpress do
  task :build do
    File.open('presentation.html', 'w') do |out|
      doc = Hexpress::Document.new(File.read('presentation.md'), [
          Hexpress::Processors::HrToSteps.new,
          Hexpress::Processors::AddImpressJs.new
        ]
      )

      out << doc.to_html
    end
  end
end
