require 'slippery'

class Hexp::Node
  def first(selector)
    select(selector).first
  end

  def delete(selector)
    replace(selector) { [] }
  end

end

def file_uri_relative(path)
  "file://#{Pathname(__FILE__).dirname.join(path)}"
end

# beige
# default
# moon
# night
# serif
# simple
# sky
# solarized

Slippery::RakeTasks.new do
  self.options = {
    type: :reveal_js,
    theme: 'sky',
    #controls: false,
    backgroundTransition: 'none',
    transition: 'none',
    history: true,
    plugins: [:notes]
  }

  processor 'head' do |head|
    head <<= H[:title, 'Web Services, Past Present Future']
    head <<= H[:link, rel: 'stylesheet', href: file_uri_relative('css/style.css')]
  end

  processor 'img' do |img|
    %w[img/ img/orig].each do |prefix|
      if File.exist?(prefix + img.attr('src'))
        img = img.attr('src', prefix + img.attr('src'))
      end
    end
    img
  end

  processor '.disclaimer' do |section|
    section.attr('data-background-color',"#dd1111")
  end

  processor 'section' do |section|
    if section.select('h2').first && section.select('h2').first.text =~ /^\d{4}$/
      section
        .replace('h2') {|h2| h2.set_tag('h1')}
        .replace('p') {|p| p.set_tag('h3')}
    else
      section
    end
  end

  processor '.expand' do |section|
    src = section.first('img').attr('src')
    section.attr('data-background', src)
      .delete('img')
  end

  self_contained
end
