require 'rb-inotify'

BUILD='bundle exec mdpress --latex -s plexus presentation.md'

class WatchTask
  def initialize(name, opts = {})
    Rake::Task.define_task name do
      Array(opts[:watch]).each do |pattern|
        notifier.watch(pattern, :modify, :create) do |event|
          system(opts[:exec])
          puts "OK"
        end
        at_exit {
          notifier.run
        }
      end
    end
  end

  def notifier
    @notifier ||= INotify::Notifier.new
  end
end

namespace :mdpress do
  WatchTask.new(
    :watch,
    :watch => [
      'presentation.md',
      'themes/plexus.css',
      'themes/plexus.html'
    ],
    :exec => BUILD
  )

  task :build do
    sh BUILD
  end
end



task :preview => 'mdpress:build' do
  require 'securerandom'
  secret = SecureRandom.hex(8)
  sh "scp -r presentation arnebrasseur@arnebrasseur.net:subdomains/www/rulu-#{secret}"
  url = "http://arnebrasseur.net/rulu-#{secret}/index.html"
  puts
  sh "chromium-browser #{url}"
end
