require 'slippery'

Slippery::RakeTasks.new do
  title "Functional Programming in Ruby | @plexus"
  type :reveal_js
  add_highlighting :default, '8.2'

  # Fathom
  #js_options scrollLength: 0, displayMode: 'single'

  # Deck.js
  # js_options extensions: ['navigation'], theme: 'neon', transition_theme: nil

  # reveal_js
  js_options theme: 'sky',
             transition: 'none',
             backgroundTransition: 'none',
             width: 1500,  #1680,
             height: 1000,  #1050
             loop: true


# beige
# default
# moon
# night
# serif
# simple
# sky
# solarized

  pack_assets

  ga = <<GA
	    var _gaq = _gaq || [];
	    _gaq.push(['_setAccount', 'UA-16178122-1']);
	    _gaq.push(['_trackPageview']);

	    (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	    })();
GA

  processor 'head' do |head|
    H[:head, head.attributes, head.children + [
        H[:meta, charset: 'utf-8'],
        H[:meta, name: 'viewport', content: 'width=1024'],
        H[:meta, "http-equiv" => 'X-UA-Compatible', content: 'IE=edge,chrome=1'],
        H[:link, rel: 'stylesheet', type: 'text/css', href: 'style.css'],
        H[:script, {type: 'text/javascript'}, ga],
      ]
    ]
  end

  processor 'section[fullscreen-img]' do |section|
    section.attr('data-background', section.attr('fullscreen-img'))
  end

  processor '.fragments, .fragments ul' do |section|
    section.map_children do |ch|
      if ch.text? || ch.tag?(:h2) || ch.tag?(:ul)
        ch
      else
        ch.add_class('fragment')
      end
    end
  end
end

task :default => 'slippery:build:index'
task :watch   => 'slippery:watch:index'
